version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: chore

  - package-ecosystem: gomod
    directory: /go
    schedule:
      interval: weekly
    labels:
      - dependencies
      - go
    commit-message:
      prefix: chore

  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python
    commit-message:
      prefix: chore
